import { TEditorConfiguration } from './core';
type TValue = {
    document: TEditorConfiguration;
    isLoading: boolean;
    loadError: string | null;
    selectedBlockId: string | null;
    selectedSidebarTab: 'block-configuration' | 'styles';
    selectedMainTab: 'editor' | 'preview' | 'json' | 'html';
    selectedScreenSize: 'desktop' | 'mobile';
    inspectorDrawerOpen: boolean;
    samplesDrawerOpen: boolean;
    currentView: 'editor' | 'mailchimp';
};
export declare function useDocument(): TEditorConfiguration;
export declare function useSelectedBlockId(): string | null;
export declare function useSelectedScreenSize(): "desktop" | "mobile";
export declare function useSelectedMainTab(): "html" | "editor" | "preview" | "json";
export declare function setSelectedMainTab(selectedMainTab: TValue['selectedMainTab']): void;
export declare function useSelectedSidebarTab(): "styles" | "block-configuration";
export declare function useInspectorDrawerOpen(): boolean;
export declare function useSamplesDrawerOpen(): boolean;
export declare function setSelectedBlockId(selectedBlockId: TValue['selectedBlockId']): void;
export declare function setSidebarTab(selectedSidebarTab: TValue['selectedSidebarTab']): void;
export declare function resetDocument(document: TValue['document']): void;
export declare function setDocument(document: TValue['document']): void;
export declare function toggleInspectorDrawerOpen(): void;
export declare function toggleSamplesDrawerOpen(): void;
export declare function setSelectedScreenSize(selectedScreenSize: TValue['selectedScreenSize']): void;
export declare function useCurrentView(): "editor" | "mailchimp";
export declare function setCurrentView(currentView: TValue['currentView']): void;
export declare function useIsLoading(): boolean;
export declare function useLoadError(): string | null;
export declare function loadTemplateFromHash(hash: string): Promise<void>;
export {};
//# sourceMappingURL=EditorContext.d.ts.map